declare namespace RMMZ {
	interface System {
		advanced: Advanced;
		airship: Vehicle;
		armorTypes: string[];
		attackMotions: AttackMotion[];
		battleBgm: Audio;
		battleback1Name: string;
		battleback2Name: string;
		battlerHue: number;
		battlerName: string;
		battleSystem: number;
		boat: Vehicle;
		currencyUnit: string;
		defeatMe: Audio;
		editMapId: number;
		elements: string[];
		equipTypes: string[];
		gameTitle: string;
		gameoverMe: Audio;
		itemCategories: boolean[];
		locale: string;
		magicSkills: number[];
		menuCommands: boolean[];
		optAutosave: boolean;
		optDisplayTp: boolean;
		optDrawTitle: boolean;
		optExtraExp: boolean;
		optFloorDeath: boolean;
		optFollowers: boolean;
		optKeyItemsNumber: boolean;
		optSideView: boolean;
		optSlipDeath: boolean;
		optTransparent: boolean;
		partyMembers: number[];
		ship: Vehicle;
		skillTypes: string[];
		sounds: Audio[];
		startMapId: number;
		startX: number;
		startY: number;
		switches: string[];
		terms: Terms;
		testBattlers: TestBattler[];
		testTroopId: number;
		tileSize: number | null;
		title1Name: string;
		title2Name: string;
		titleBgm: Audio;
		titleCommandWindow: CommandWindow;
		variables: string[];
		versionId: number;
		victoryMe: Audio;
		weaponTypes: string[];
		windowTone: [number, number, number, number];
		optSplashScreen: boolean;
		hasEncryptedImages: boolean;
		hasEncryptedAudio: boolean;
		encryptionKey: string;
		optMessageSkip: boolean;
	}
}
